# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_category_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='anu',
        ),
    ]
