# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20170809_0317'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
